version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CultivaSP"
    labels:
      - "dependencies"
      - "npm"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "node"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
