#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtiene el nombre de la rama actual
current_branch=$(git branch --show-current)

# Verifica si estás intentando subir a main o develop
if [ "$current_branch" = "main" ] || [ "$current_branch" = "develop" ]; then
  echo ""
  echo "🚫 ACCESO DENEGADO 🚫"
  echo "Por reglas del proyecto, no puedes hacer un 'push' directo a la rama: $current_branch"
  echo "👉 Crea una nueva rama (ej. feature/nueva-vista) y utiliza un Pull Request."
  echo ""
  exit 1
fi